db:
    synchronize: true

mailing:
    enabled: false
    from: "no-reply@student-mgmt-system"
    clientBasePath: "http://localhost:4200"
    smtp:
        host: "smtp.mailtrap.io"
        useSecureConnection: false
        username: "3f094336feeea2"
        password: "5c31da72a84fc4"
        port: 2525

logger:
    levels:
        - error
        - warn
        - debug
        - verbose
    requests: false
    dbErrors: true
